name: cleany
description: A CLI tool to generate Clean Architecture feature structure for Flutter projects
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.7.0 
  yaml: ^3.1.3







dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0


executables:
  cleany: cleany


