name: cleany
description: A CLI tool to generate Clean Architecture feature structure for Flutter projects
version: 0.0.43
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.7.0 
  flutter_dotenv: ^6.0.0
  multiple_result: ^5.2.0
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  dart_mappable: ^4.6.1
  dio: ^5.9.0
  retrofit: ^4.9.1
  easy_localization: ^3.0.8
  flutter_secure_storage: ^9.2.4
  sizer: ^3.1.3
  supabase_flutter: ^2.10.3
  get_storage: ^2.1.1
  get_it: ^9.1.1
  go_router: ^17.0.0
  injectable: ^2.7.0
  equatable: ^2.0.7
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0






dev_dependencies:
  build_runner: ^2.10.4
  dart_mappable_builder: ^4.6.1
  flutter_lints: ^6.0.0
  injectable_generator: ^2.9.1
  lints: ^6.0.0
  retrofit_generator: ^10.2.0
  test: ^1.27.0


executables:
  cleany: cleany




  # dart pub global deactivate cleany


# dart pub global activate --source path .

# dart pub global activate --source git https://github.com/fahad0100/cleany
# cleany auth



# # 2. ثبّت المكتبات
# dart pub get

# # 3. الغي التفعيل القديم
# dart pub global deactivate cleany 2>/dev/null || true
# dart pub global deactivate flutter_folder_cli 2>/dev/null || true

# # 4. فعّل من جديد
# dart pub global activate --source path .

# # 5. جرّب
# cleany --help